# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z-YYG8TcNgALefVQbbnOWle0_BF500Rz
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
#  
# import pickle
# import streamlit as st
# import pandas as pd
# from sklearn.preprocessing import  LabelEncoder
# import xgboost as xgb
# import numpy as np
# 
# #loading the trained model
# pickle_in = open('classifier.pkl', 'rb') 
# classifier = pickle.load(pickle_in)
# 
# st.header("Fish Weight Prediction App")
# st.text_input("Enter your Name: ", key="name")
# data = pd.read_csv("1. Property Sales data")
# 
# encoder = LabelEncoder()
# encoder.classes_ = np.load('classes.npy',allow_pickle=True)
# 
# # loading the trained model
# pickle_in = open('classifier.pkl', 'rb') 
# classifier = pickle.load(pickle_in)
# 
# @st.cache()
# 
# if st.checkbox('Show dataframe'):
#     data
# 
# st.subheader("Please Enter Post Code")
# PostCode = st.number_input("PostCode")
# 
# if st.button('Make Prediction'):
#     input_species = encoder.transform(np.expand_dims(inp_species, -1))
#     inputs = np.expand_dims(
#         [int(PostCode)], 0)
#     prediction = classifier.predict(inputs)
#     print("final pred", np.squeeze(prediction, -1))
#     st.write(f"Your fish weight is: {np.squeeze(prediction, -1)} Gram")
# 
# 
# 
#